export const themeConfig = {
  light: {
    background: "white",
    foreground: "#1a1a1a",
    primary: "#0070f3",
    primaryForeground: "white",
    secondary: "#f5f5f5",
    secondaryForeground: "#1a1a1a",
    accent: "#f0f7ff",
    accentForeground: "#0070f3",
    muted: "#f5f5f5",
    mutedForeground: "#737373",
    border: "#e5e5e5",
    card: "white",
    cardForeground: "#1a1a1a",
    destructive: "#ff4d4f",
    destructiveForeground: "white",
    success: "#52c41a",
    successForeground: "white",
    warning: "#faad14",
    warningForeground: "white",
  },
  dark: {
    background: "#121212",
    foreground: "#f5f5f5",
    primary: "#0070f3",
    primaryForeground: "white",
    secondary: "#1f1f1f",
    secondaryForeground: "#f5f5f5",
    accent: "#1a365d",
    accentForeground: "#0070f3",
    muted: "#1f1f1f",
    mutedForeground: "#a3a3a3",
    border: "#2a2a2a",
    card: "#1f1f1f",
    cardForeground: "#f5f5f5",
    destructive: "#ff4d4f",
    destructiveForeground: "white",
    success: "#52c41a",
    successForeground: "white",
    warning: "#faad14",
    warningForeground: "white",
  }
} 